### ISSUE TITLE
ფოლის ღილაკი და პანელი

### ISSUE THREAD

**Issue by archiltavdgiridze** [archiltavdgiridze/mafia#12]
- ასაწყობია ფოლის ღილაკი F და პანელი რომელიც ღილაკზე კლიკის შემდეგ გამოჩნდება. 
- შიგნით უნდა გამოჩნდეს მოთამაშეების ჩამონათვალი და – 1 +  მთვლელი.
- კომპონენტმა წინასწარ მონიშნული ფოლების რაოდენობა უნდა შეინახოს და როდესაც მთვლელით მიაღწევს შენახულ რიცხვს, უნდა გააწითლოს მოთამაშის სახელი (ანუ გავარდნის აღმნიშვნელი)
 
![image](https://github.com/archiltavdgiridze/mafia/assets/113973004/6bb371e5-e23c-4a65-a09f-2dc4815c1324)

**Comment by jeliaaa** [comment]
davamate reusable componentad romelsac survilisamebr gamoidzaxeb nebismier componentshi, unda gakontroldes misi shigtavsi da shida contenti unda dasavdes sessionstorageshi magas mivxedav
