### ISSUE TITLE
ტაიმერიან სასაუბრო კომპონენტში ტაიმერის დარესტარტების ლოგიკა

### ISSUE THREAD

**Issue by archiltavdgiridze** [archiltavdgiridze/mafia#8]
როცა მომდევნო მოთამაშის ღილაკს დააწვება წამყვანი, უნდა დარესტარტდეს აწ უკვე დაწყებული ტაიმერი და ისევ წინასწარ მონიშნულ დროზე დაყენდეს.

**Comment by jeliaaa** [comment]
vso

**Comment by jeliaaa** [comment]
.
